#!/bin/sh

#Remove "#" from following two lines, if you'd like to use j2sdk.
#JAVA_HOME=/usr/lib/j2sdk1.4/;export JAVA_HOME
#PATH=$JAVA_HOME/bin:$PATH; export PATH

#ASTAH_HOME=/usr/local/share/astah_community
ASTAH_HOME=`dirname $0`
ASTAH_JAR=astah-community.jar

CLASSPATH=$ASTAH_HOME/$ASTAH_JAR

JAVA_OPTS="-Xms16m -Xmx384m"

java $JAVA_OPTS -jar $ASTAH_HOME/$ASTAH_JAR  $1 $2 $3
